# Generated by Django 6.0.6 on 2026-06-15 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('theme', models.CharField(blank=True, help_text='e.g., Arrival & The Green Bazaar', max_length=200)),
                ('early_start_banner', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True, help_text="User's personal saved notes for this day")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='StopBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.PositiveIntegerField()),
                ('time_label', models.CharField(help_text='e.g., 1:30 PM — First stop', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('zoom_level', models.PositiveIntegerField(default=15)),
                ('cost_local', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('meal_type', models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=50)),
                ('meal_name', models.CharField(blank=True, max_length=200)),
                ('meal_desc', models.TextField(blank=True)),
                ('meal_price_label', models.CharField(blank=True, max_length=100)),
                ('meal_recommendation', models.TextField(blank=True, help_text='e.g. Tip for Eesa or menu recommendation')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of string badges')),
                ('color_hex', models.CharField(default='#E67E22', help_text='Color for map marker', max_length=7)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='itinerary.dayitinerary')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='PlaceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(blank=True, max_length=255)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('reviews_json', models.JSONField(blank=True, default=list, help_text='Cache of 10 recent reviews')),
                ('photos_json', models.JSONField(blank=True, default=list, help_text='Cache of image URLs')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='place_detail', to='itinerary.stopblock')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Family Adventure', max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dayitinerary',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='itinerary.trip'),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Packing List', max_length=100)),
                ('item_text', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='itinerary.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('Flight', 'Flight'), ('Hotel', 'Hotel/Airbnb'), ('Activity', 'Activity/Driver'), ('Restaurant', 'Restaurant')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('confirmation_number', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='bookings/')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='itinerary.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g., Husband, Wife, Toddler (3yo)', max_length=100)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='itinerary.trip')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dayitinerary',
            unique_together={('trip', 'day_number')},
        ),
    ]
