# Generated by Django 6.0.6 on 2026-06-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopblock',
            name='end_time_of_day',
            field=models.TimeField(blank=True, help_text='e.g. 15:00:00', null=True),
        ),
        migrations.AddField(
            model_name='stopblock',
            name='start_time_of_day',
            field=models.TimeField(blank=True, help_text='e.g. 13:30:00', null=True),
        ),
        migrations.CreateModel(
            name='StopPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stops/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photos', to='itinerary.stopblock')),
            ],
        ),
    ]
