# Generated by Django 6.0.6 on 2026-06-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0004_trip_creation_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripcreationjob',
            name='attendees_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='stopblock',
            name='meal_recommendation',
            field=models.TextField(blank=True, help_text='e.g. Tip for young children or menu recommendation'),
        ),
    ]
